### ISSUE TITLE
modelnet_set_texture.mlx

### ISSUE THREAD

**Issue by MartinSmeyer** [wangg12/mx-DeepIM#1]
I downloaded ModelNet40. Could you tell me where to get the modelnet_set_texture.mlx / modelnet_set_texture_flat.mlx from?

**Comment by wangg12** [comment]
@speyside42 Open meshlab and your 3D model, generate texture with a proper method (triangular, flat, etc.). Then go to "Filters/Show current filter script" and save the script.

A .mlx script may be like this.
[modelnet_set_texture.mlx.zip](https://github.com/wangg12/mx-DeepIM/files/2422955/modelnet_set_texture.mlx.zip)

**Comment by MartinSmeyer** [comment]
thank you!
