### ISSUE TITLE
Prepare data for LINEMOD-OCC

### ISSUE THREAD

**Issue by tim885** [wangg12/mx-DeepIM#4]
Hi, 
Can you kindly offer the script to prepare data for LINEMOD Occlusion training? I tried but didn't figure it out. Thanks a lot!     
Best,

**Comment by wangg12** [comment]
I will modify the scripts according to the released code and write a guide to prepare data for LINEMOD Occlusion.

**Comment by wangg12** [comment]
@tim885 Updated preparing data for Occlusion.

**Comment by tim885** [comment]
Thanks a lot! That's very helpful.

**Comment by wangg12** [comment]
@tim885 If you find any bugs, please feel free to post them here to help me improve it.
